version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: tarefas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"  # Porta do host : Porta do container


  app:
    build: .
    ports:
      - "8501:8501" # Porta do host : Porta do container
    depends_on:
      - db
    volumes:
      - ./:/app

volumes:
  db_data:
